version: '3'

services:

  back:
    container_name: resibacki
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
        - .:/app
    restart: always
